# image will be published to ghcr.io/<user>/<name>
name: plasma-nvidia-38-laptop
# description will be included in the image's metadata
description: Based on kinoite with Fedora 38, Plasma, and nvidia driver support

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-nvidia
image-version: 38 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr # copy static configurations
                  #
                  # copies config/files/usr into your image's /usr
                  #
                  # configuration you wish to end up in /etc/ on the booted system
                  # should be added into /usr/etc/ as that is the proper "distro"
                  # config directory on ostree. Read more in the files module's README

  - type: rpm-ostree
    repos:
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
      - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-%OS_VERSION%.noarch.rpm
      - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-%OS_VERSION%.noarch.rpm

      # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      - ctags
      - curl
      - kitty
      - meld
      - neovim
      - nodejs
      - npm
      - openssh-askpass
      - podman
      - podman-compose
      - python3-neovim
      - vlc
      - zsh

      # Tailscale Repo
      - tailscale

      # RPM Fusion
      - fedora-workstation-repositories
      - rpmfusion-free-release-tainted
      - rpmfusion-nonfree-release-tainted

    remove:
      - akregator
      - calligra-core
      - falkon
      - firefox
      - firefox-langpacks
      - juk
      - k3b
      - kaddressbook
      - kamoso
      - kget
      - kmahjongg
      - kmail
      - kmines
      - kontact
      - konversation
      - korganizer
      - kpat
      - ktorrent


  - type: bling # configure what to pull in from ublue-os/bling
    install:
      - justfiles # add "!include /usr/share/ublue-os/just/100-bling.just"
                  # in your custom.just (added by default) or local justfile
      - laptop


  - type: yafti
    custom-flatpaks:
      - Flatseal: com.github.tchx84.Flatseal
      - Discord: com.discordapp.Discord
      - Signal: org.signal.Signal
      - Zulip: org.zulip.Zulip
      - GitKraken: com.axosoft.GitKraken
      - Obisidan: md.obsidian.Obsidian
      - OBS Studio: com.obsproject.Studio
      - Todoist: com.todoist.Todoist
      - XMind: net.xmind.ZEN
      - OnlyOffice: org.onlyoffice.desktopeditors

  - type: script
    scripts:
      # this sets up the proper policy & signing files for signed images to work
      - signing.sh
